### ISSUE TITLE
Create model: Penalty

### ISSUE THREAD

**Issue by ghost** [DelegacionUC3M/prestamos#2]
Implementar modelo de Sanción.

- [x] Clase sanción
- [x] Constructor: función __init__
- [x] Print: función __repr__

[Link a la wiki](https://delegacion.uc3m.es/wiki/doku.php?id=comision_tic:apps:iasad:inicio)

**Comment by Patataman** [comment]
En la función "repr"  haces `return {'id':self.id, 'user':self.user, 'loan_id':self.loan_id, 'sanction_date':self.sanction_date, 'penalty_date':self.penalty_date}`

En este caso **estás devolviendo un diccionario** y lo que se busca con esta función es que cuando se imprima el objeto, te diga las características del mismo, por lo que **debes devolver un string**. Asi que me voy a tomar la libertad de desmarcar el check del print xD

Si sabes Java, es lo mismo que la función toString.

**Comment by Drimmark** [comment]
Eso que dices no es estrictamente cierto. La función `__repr__` es la función a la que python llama internamente cuando tiene que generar un string a partir del objeto (lo cual no es, necesariamente, lo mismo que decir que cuando imprima el objeto).

La gracia de devolver un diccionario en lugar de un string es que el diccionario ya tiene implementada la función `__repr__` de forma que devuelva el diccionario en formato string (literalmente lo que nosotros devolvemos en el return). Al tener implementada la función de esta manera, la conversión a JSON, por ejemplo, es directa (**la función `__repr__` del objeto `dict` -un diccionario- es la representación JSON de ese diccionario**).

De esta forma, devolver un diccionario de esa manera te lleva a generar un string del tipo que construirías manualmente pero de forma más limpia. El hecho de que lo hayan hecho así es que en la elaboración de los modelos del lunes les comenté que así era más cómodo. Realmente, al ser esta una aplicación monolítica no es especialmente relevante, pero de ser una API, nuestro endpoint podría devolver directamente el objeto (que al intentar generar un string encontraría el diccionario que generaría un JSON).

**Comment by Drimmark** [comment]
Lo que si he estado pensando es que, a pesar de lo que hablamos el lunes, es preferible que el constructor no de valores por defecto a los atributos que son obligatorios del modelo (como ha hecho @Patataman en su [modelo](https://github.com/DelegacionUC3M/prestamos/blob/master/models/loan.py)). Así vemos rápidamente en el constructor que campos son obligatorios y evitamos que la excepción se produzca en la base de datos.

¿Podrías cambiarlo @servinagrero ?

¡Gracias!
